import type { GeneratedSuite, InputModel, TestCase } from "@/lib/edgeproof/types";

function inferInputModel(directions: string, referenceCode: string): InputModel {
  const text = `${directions}\n${referenceCode}`.toLowerCase();

  if (/(list|array|vector)/.test(text)) {
    return "array";
  }

  if (/(string|substring|palindrome|char)/.test(text)) {
    return "string";
  }

  if (/(graph|tree|node|edge)/.test(text)) {
    return "graph";
  }

  if (/(matrix|grid)/.test(text)) {
    return "matrix";
  }

  return "number";
}

function inferModelFromExample(exampleInput: unknown): InputModel | null {
  if (exampleInput === null || exampleInput === undefined) return null;

  if (Array.isArray(exampleInput)) return "array";
  if (typeof exampleInput === "string") return "string";
  if (typeof exampleInput === "number") return "number";

  if (typeof exampleInput === "object") {
    const obj = exampleInput as Record<string, unknown>;
    if (Array.isArray(obj.arr)) return "array";
    if (typeof obj.s === "string") return "string";
    if (typeof obj.n === "number") return "number";
    if (Array.isArray(obj.matrix)) return "matrix";
    if (Array.isArray(obj.edges)) return "graph";
  }

  return null;
}

function extractConstraintHints(directions: string) {
  const hints: string[] = [];

  if (/non[- ]?negative/i.test(directions)) {
    hints.push("non_negative");
  }

  if (/positive/i.test(directions)) {
    hints.push("positive");
  }

  if (/sorted/i.test(directions)) {
    hints.push("sorted");
  }

  if (/unique|distinct/i.test(directions)) {
    hints.push("unique");
  }

  if (/(10\^\d+|1e\d+|large|big input|up to \d+)/i.test(directions)) {
    hints.push("high_bounds");
  }

  return hints;
}

function buildCase(id: string, category: string, input: unknown, expected: unknown, rationale: string): TestCase {
  return {
    id,
    category,
    input,
    expected: expected as any,
    rationale,
  };
}

function fnv1a32(text: string) {
  const str = String(text || "");
  let hash = 0x811c9dc5;
  for (let i = 0; i < str.length; i += 1) {
    hash ^= str.charCodeAt(i);
    hash = (hash + (hash << 1) + (hash << 4) + (hash << 7) + (hash << 8) + (hash << 24)) >>> 0;
  }
  return hash >>> 0;
}

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function rng() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function randomInt(rng: () => number, min: number, max: number) {
  const lo = Math.ceil(min);
  const hi = Math.floor(max);
  return Math.floor(rng() * (hi - lo + 1)) + lo;
}

function pickOne<T>(rng: () => number, list: T[]): T {
  return list[Math.floor(rng() * list.length)];
}

function stableKey(value: unknown) {
  // Inputs are generated by us, so insertion order is stable.
  // This is used only for dedupe across generated cases.
  return JSON.stringify(value);
}

function uniquePushByInput(
  target: Array<{ category: string; input: unknown; rationale: string; expected?: unknown }>,
  seenInputKeys: Set<string>,
  entry: { category: string; input: unknown; rationale: string; expected?: unknown }
) {
  const key = stableKey(entry.input);
  if (seenInputKeys.has(key)) return false;
  seenInputKeys.add(key);
  target.push(entry);
  return true;
}

function numberBounds(constraints: string[]) {
  const high = constraints.includes("high_bounds");
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");

  let min = high ? -1000000000 : -10000;
  const max = high ? 1000000000 : 10000;

  if (positiveOnly) {
    min = Math.max(min, 1);
  } else if (nonNegative) {
    min = Math.max(min, 0);
  }

  return { min, max };
}

function generateNumberVariants(constraints: string[], rng: () => number) {
  const { min, max } = numberBounds(constraints);
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");

  const base = [0, 1, 2, 7, 10, 42, 999, max, max - 1, min, min + 1];
  const filtered = base.filter((n) => {
    if (positiveOnly) return n > 0;
    if (nonNegative) return n >= 0;
    return true;
  });

  // Add a few deterministic pseudo-random draws.
  for (let i = 0; i < 20; i += 1) {
    let candidate = randomInt(rng, min, max);
    if (positiveOnly) candidate = Math.max(1, Math.abs(candidate));
    if (nonNegative) candidate = Math.max(0, candidate);
    filtered.push(candidate);
  }

  return Array.from(new Set(filtered));
}

function generateStringVariants(rng: () => number) {
  const presets = [
    "",
    "a",
    "A",
    "0",
    "   ",
    "a,b.c!",
    "naïve café",
    "racecar",
    "abababab",
    "a".repeat(256),
    "abc".repeat(2000),
  ];

  const alphabets = [
    "abcdefghijklmnopqrstuvwxyz",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "0123456789",
    "abcdefghijklmnopqrstuvwxyz0123456789",
    " \t\n",
    "-_.,:;!?()[]{}<>/\\'\"",
  ];

  const out = [...presets];

  for (let i = 0; i < 40; i += 1) {
    const alphabet = pickOne(rng, alphabets);
    const len = pickOne(rng, [0, 1, 2, 3, 5, 8, 13, 21, 55, 144, randomInt(rng, 0, 300)]);
    let s = "";
    for (let j = 0; j < len; j += 1) {
      s += alphabet.charAt(Math.floor(rng() * alphabet.length));
    }
    out.push(s);
  }

  return Array.from(new Set(out));
}

function generateArrayVariants(constraints: string[], rng: () => number, baseArray?: unknown[]) {
  const { min, max } = numberBounds(constraints);
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");
  const sorted = constraints.includes("sorted");
  const unique = constraints.includes("unique");

  const candidates: number[][] = [];

  // Structured patterns (kept small; fuzz fills the rest)
  candidates.push([]);

  const mid = nonNegative ? 0 : positiveOnly ? 1 : 0;
  const allSame = positiveOnly ? 1 : 0;

  if (!positiveOnly) {
    candidates.push([0]);
  }

  candidates.push([1]);

  if (!nonNegative && !positiveOnly) {
    candidates.push([-1]);
  }

  candidates.push([max]);
  candidates.push([min]);

  if (positiveOnly) {
    candidates.push([1, 2, 3, 4, 5]);
    candidates.push([5, 4, 3, 2, 1]);
  } else if (nonNegative) {
    candidates.push([0, 1, 2, 3, 4]);
    candidates.push([4, 3, 2, 1, 0]);
  } else {
    candidates.push([1, 2, 3, 4, 5]);
    candidates.push([5, 4, 3, 2, 1]);
  }

  candidates.push(Array.from({ length: 5 }, () => allSame));

  if (!nonNegative && !positiveOnly) {
    candidates.push([1, -1, 1, -1, 1, -1]);
    candidates.push([min, 0, max]);
    candidates.push(Array.from({ length: 50 }, (_, i) => (i % 7) - 3));
  } else {
    candidates.push([1, 2, 1, 2, 1, 2]);
    candidates.push([min, mid, max]);
    candidates.push(Array.from({ length: 50 }, (_, i) => i % 7));
  }

  if (Array.isArray(baseArray)) {
    const asNumbers = baseArray.filter((v) => typeof v === "number") as number[];
    candidates.push(asNumbers.slice(0, 0));
    candidates.push(asNumbers.slice(0, 1));
    candidates.push(asNumbers.slice());
    candidates.push(asNumbers.slice().reverse());
  }

  const lengthChoices = constraints.includes("high_bounds")
    ? [0, 1, 2, 3, 5, 8, 13, 21, 55, 120, 250, 500]
    : [0, 1, 2, 3, 5, 8, 13, 21, 55, 120];

  // Random fuzz arrays
  for (let i = 0; i < 140; i += 1) {
    const len = pickOne(rng, lengthChoices);
    const arr: number[] = [];
    const seen = new Set<number>();

    for (let j = 0; j < len; j += 1) {
      let val: number;

      const mode = rng();
      if (mode < 0.65) {
        val = randomInt(rng, -10, 10);
      } else if (mode < 0.9) {
        val = randomInt(rng, -1000, 1000);
      } else {
        val = rng() < 0.5 ? min : max;
      }

      if (positiveOnly) val = Math.max(1, Math.abs(val));
      if (nonNegative) val = Math.max(0, val);

      if (unique) {
        let attempts = 0;
        while (seen.has(val) && attempts < 20) {
          val = randomInt(rng, nonNegative || positiveOnly ? 0 : min, max);
          if (positiveOnly) val = Math.max(1, Math.abs(val));
          if (nonNegative) val = Math.max(0, val);
          attempts += 1;
        }
        seen.add(val);
      }

      arr.push(val);
    }

    if (sorted) {
      arr.sort((a, b) => a - b);
    }

    candidates.push(arr);
  }

  return candidates;
}

function generateMatrixVariants(constraints: string[], rng: () => number, baseMatrix?: unknown) {
  const { min, max } = numberBounds(constraints);
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");
  const mid = nonNegative ? 0 : positiveOnly ? 1 : 0;

  const dims = constraints.includes("high_bounds")
    ? [
        [0, 0],
        [1, 1],
        [1, 5],
        [5, 1],
        [2, 3],
        [10, 10],
        [30, 30],
      ]
    : [
        [0, 0],
        [1, 1],
        [1, 5],
        [5, 1],
        [2, 3],
        [10, 10],
      ];

  const candidates: number[][][] = [];
  candidates.push([]);
  candidates.push([[1]]);
  candidates.push([[1, 2, 3, 4]]);
  candidates.push([[1], [2], [3]]);
  candidates.push([
    [min, mid, max],
    [max, mid, min],
  ]);

  if (Array.isArray(baseMatrix)) {
    candidates.push(baseMatrix as any);
  }

  for (let i = 0; i < 80; i += 1) {
    const [rows, cols] = pickOne(rng, dims as any);
    const matrix: number[][] = [];
    for (let r = 0; r < rows; r += 1) {
      const row: number[] = [];
      for (let c = 0; c < cols; c += 1) {
        const mode = rng();

        let val: number;
        if (mode < 0.7) val = randomInt(rng, -10, 10);
        else if (mode < 0.95) val = randomInt(rng, -1000, 1000);
        else val = rng() < 0.5 ? min : max;

        if (positiveOnly) val = Math.max(1, Math.abs(val));
        if (nonNegative) val = Math.max(0, val);

        row.push(val);
      }
      matrix.push(row);
    }
    candidates.push(matrix);
  }

  return candidates;
}

function generateGraphVariants(
  constraints: string[],
  rng: () => number,
  baseGraph?: { n: number; edges: number[][] } | null
) {
  const high = constraints.includes("high_bounds");
  const maxN = high ? 400 : 80;

  const candidates: Array<{ n: number; edges: number[][] }> = [];
  candidates.push({ n: 0, edges: [] });
  candidates.push({ n: 1, edges: [] });
  candidates.push({ n: 5, edges: [
    [0, 1],
    [3, 4],
  ] });
  candidates.push({ n: 4, edges: [
    [0, 1],
    [1, 2],
    [2, 3],
    [3, 0],
  ] });
  candidates.push({ n: 3, edges: [[1, 1]] });
  candidates.push({ n: 3, edges: [
    [0, 1],
    [0, 1],
    [1, 2],
  ] });

  if (baseGraph && typeof baseGraph === "object" && typeof baseGraph.n === "number" && Array.isArray(baseGraph.edges)) {
    candidates.push({ n: baseGraph.n, edges: baseGraph.edges });
  }

  for (let i = 0; i < 90; i += 1) {
    const n = pickOne(rng, [0, 1, 2, 3, 5, 8, 13, randomInt(rng, 1, maxN)]);
    const edges: number[][] = [];

    const mode = rng();
    if (mode < 0.25) {
      // chain
      for (let k = 0; k < Math.max(0, n - 1); k += 1) edges.push([k, k + 1]);
    } else if (mode < 0.5) {
      // star
      for (let k = 1; k < n; k += 1) edges.push([0, k]);
    } else if (mode < 0.65) {
      // cycle
      for (let k = 0; k < n; k += 1) edges.push([k, (k + 1) % Math.max(1, n)]);
    } else {
      // random sparse
      const edgeCount = n <= 1 ? 0 : randomInt(rng, 0, Math.min(n * 3, 600));
      for (let e = 0; e < edgeCount; e += 1) {
        edges.push([
          randomInt(rng, 0, Math.max(0, n - 1)),
          randomInt(rng, 0, Math.max(0, n - 1)),
        ]);
      }
    }

    candidates.push({ n, edges });
  }

  return candidates;
}

function buildMutatedObjectCases({
  baseInput,
  constraints,
  requiredCount,
  rng,
}: {
  baseInput: Record<string, unknown>;
  constraints: string[];
  requiredCount: number;
  rng: () => number;
}) {
  const keys = baseInput && typeof baseInput === "object" ? Object.keys(baseInput) : [];
  const cases: Array<{ category: string; input: unknown; rationale: string; expected?: unknown }> = [];
  const seen = new Set<string>();

  uniquePushByInput(cases, seen, {
    category: "example baseline",
    input: baseInput,
    rationale: "Uses your provided example input as a sanity-check baseline.",
  });

  const perKeyVariants = keys.map((key) => {
    const value = baseInput[key];

    if (Array.isArray(value)) {
      return {
        key,
        kind: "array",
        variants: generateArrayVariants(constraints, rng, value as any),
      };
    }

    if (typeof value === "number") {
      return {
        key,
        kind: "number",
        variants: generateNumberVariants(constraints, rng),
      };
    }

    if (typeof value === "string") {
      return {
        key,
        kind: "string",
        variants: generateStringVariants(rng),
      };
    }

    if (value && typeof value === "object" && Array.isArray((value as any).matrix)) {
      return {
        key,
        kind: "matrix-wrapper",
        variants: generateMatrixVariants(constraints, rng, (value as any).matrix).map((matrix) => ({
          ...(value as any),
          matrix,
        })),
      };
    }

    if (value && typeof value === "object" && typeof (value as any).n === "number" && Array.isArray((value as any).edges)) {
      return {
        key,
        kind: "graph-wrapper",
        variants: generateGraphVariants(constraints, rng, value as any).map((g) => ({
          ...(value as any),
          n: g.n,
          edges: g.edges,
        })),
      };
    }

    return {
      key,
      kind: typeof value,
      variants: [value],
    };
  });

  // One-field-at-a-time mutations (keeps schema stable and is easy to debug).
  for (const entry of perKeyVariants) {
    if (cases.length >= requiredCount) break;

    const limit = entry.variants.length > 80 ? 80 : entry.variants.length;
    for (let i = 0; i < limit; i += 1) {
      if (cases.length >= requiredCount) break;
      const nextInput = { ...baseInput, [entry.key]: entry.variants[i] };
      uniquePushByInput(cases, seen, {
        category: `mutate ${entry.key} (${entry.kind})`,
        input: nextInput,
        rationale: `Mutates field '${entry.key}' while keeping other fields constant.`,
      });
    }
  }

  // Random multi-field mutations to increase diversity.
  let guard = 0;
  while (cases.length < requiredCount && guard < requiredCount * 40) {
    guard += 1;
    const changes = Math.min(3, Math.max(1, randomInt(rng, 1, Math.max(1, keys.length))));
    const next: Record<string, unknown> = { ...baseInput };

    for (let i = 0; i < changes; i += 1) {
      const entry = pickOne(rng, perKeyVariants as any);
      if (!entry.variants.length) continue;
      next[entry.key] = pickOne(rng, entry.variants);
    }

    uniquePushByInput(cases, seen, {
      category: "fuzz mutation",
      input: next,
      rationale: "Randomly mutates 1–3 fields to discover less obvious interactions.",
    });
  }

  return cases.slice(0, requiredCount);
}

function generateArrayCases(constraints: string[]) {
  const sortedA = constraints.includes("sorted") ? [1, 2, 3, 4] : [4, 1, 3, 2];
  const sortedB = constraints.includes("sorted") ? [1, 1, 2, 3] : [3, 1, 1, 2];
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");

  const mixedValues = positiveOnly
    ? [3, 1, 2, 5, 8]
    : nonNegative
      ? [3, 1, 0, 5, 8]
      : [3, -1, 0, 5, -8];

  const alternatingValues = positiveOnly
    ? [10, 20, 30, 40, 50, 60]
    : nonNegative
      ? [0, 10, 0, 20, 0, 30]
      : [-10, 10, -20, 20, -30, 30];

  const boundaryValues = positiveOnly
    ? [1, 1000000000]
    : nonNegative
      ? [0, 1000000000]
      : [-1000000000, 0, 1000000000];

  const longValues = Array.from({ length: 1000 }, (_, i) => (positiveOnly ? (i % 17) + 1 : i % 17));

  return [
    ["empty input", { arr: [] }, "depends-on-spec", "Checks base behavior with no elements."],
    ["single element", { arr: [7] }, "depends-on-spec", "Verifies minimal valid non-empty size."],
    ["small mixed values", { arr: mixedValues }, "depends-on-spec", "Combines boundary-like values to stress assumptions."],
    ["already sorted", { arr: sortedA }, "depends-on-spec", "Ensures sorted input does not mask logic issues."],
    ["duplicates", { arr: sortedB }, "depends-on-spec", "Checks duplicate-handling behavior."],
    ["all equal", { arr: [9, 9, 9, 9, 9] }, "depends-on-spec", "Detects assumptions about variance."],
    ["alternating pattern", { arr: alternatingValues }, "depends-on-spec", "Catches parity and pattern-based logic mistakes."],
    ["boundary extremes", { arr: boundaryValues }, "depends-on-spec", "Stresses integer boundary behavior."],
    ["long input", { arr: longValues }, "depends-on-spec", "Targets performance and repeated-pattern handling."],
  ];
}

function generateNumberCases(constraints: string[]) {
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");

  const belowZeroValue = positiveOnly ? 1 : nonNegative ? 0 : -7;
  const belowZeroCategory = positiveOnly || nonNegative ? "lower boundary" : "negative value";
  const belowZeroRationale =
    positiveOnly || nonNegative
      ? "Validates boundary handling near zero."
      : "Validates sign handling and validation rules.";

  return [
    ["zero", { n: 0 }, "depends-on-spec", "Zero is often a corner case."],
    ["one", { n: 1 }, "depends-on-spec", "Smallest common positive integer."],
    [belowZeroCategory, { n: belowZeroValue }, "depends-on-spec", belowZeroRationale],
    ["small positive", { n: 7 }, "depends-on-spec", "Simple correctness anchor."],
    ["large positive", { n: 1000000 }, "depends-on-spec", "Checks behavior near scale limits."],
    ["near overflow", { n: 2147483647 }, "depends-on-spec", "Stresses boundary integer arithmetic."],
    ["repeated run value", { n: 42 }, "depends-on-spec", "Useful for deterministic checks and idempotence."],
  ];
}

function generateStringCases() {
  return [
    ["empty string", { s: "" }, "depends-on-spec", "Ensures zero-length handling is explicit."],
    ["single char", { s: "a" }, "depends-on-spec", "Minimal non-empty string."],
    ["mixed case", { s: "AbCdEf" }, "depends-on-spec", "Tests case-sensitivity assumptions."],
    ["whitespace only", { s: "   " }, "depends-on-spec", "Verifies trimming/splitting behavior."],
    ["punctuation", { s: "a,b.c!" }, "depends-on-spec", "Covers non-alphanumeric characters."],
    ["unicode", { s: "naive cafe" }, "depends-on-spec", "Checks whether implementation assumes ASCII only."],
    ["palindrome", { s: "racecar" }, "depends-on-spec", "Common branch for symmetry logic."],
    ["very long", { s: "abc".repeat(5000) }, "depends-on-spec", "Stresses time and memory complexity."],
  ];
}

function generateMatrixCases(constraints: string[] = []) {
  const positiveOnly = constraints.includes("positive");
  const nonNegative = constraints.includes("non_negative");

  const signMixMatrix = positiveOnly
    ? [[1, 2], [3, 4]]
    : nonNegative
      ? [[0, 0], [3, 4]]
      : [[-1, -2], [3, 4]];

  const signMixRationale = positiveOnly
    ? "Small positive values matrix for baseline 2D behavior."
    : nonNegative
      ? "Includes zeros to stress identity/neutral-element assumptions."
      : "Verifies sign-sensitive behavior.";

  return [
    ["empty matrix", { matrix: [] }, "depends-on-spec", "Validates no-row behavior."],
    ["single cell", { matrix: [[1]] }, "depends-on-spec", "Minimal 2D input case."],
    ["single row", { matrix: [[1, 2, 3, 4]] }, "depends-on-spec", "Checks row-only loops."],
    ["single column", { matrix: [[1], [2], [3]] }, "depends-on-spec", "Checks column-only loops."],
    ["rectangular", { matrix: [[1, 2, 3], [4, 5, 6]] }, "depends-on-spec", "Ensures non-square logic works."],
    ["sign mix", { matrix: signMixMatrix }, "depends-on-spec", signMixRationale],
    [
      "large matrix",
      { matrix: Array.from({ length: 100 }, () => Array.from({ length: 100 }, () => 1)) },
      "depends-on-spec",
      "Targets algorithmic scalability.",
    ],
  ];
}

function generateGraphCases() {
  return [
    ["empty graph", { n: 0, edges: [] }, "depends-on-spec", "Validates base graph with no nodes."],
    ["single node", { n: 1, edges: [] }, "depends-on-spec", "Checks trivial connectivity."],
    [
      "disconnected",
      { n: 5, edges: [[0, 1], [3, 4]] },
      "depends-on-spec",
      "Ensures disconnected components are handled.",
    ],
    [
      "simple cycle",
      { n: 4, edges: [[0, 1], [1, 2], [2, 3], [3, 0]] },
      "depends-on-spec",
      "Targets cycle detection branches.",
    ],
    ["self loop", { n: 3, edges: [[1, 1]] }, "depends-on-spec", "Captures self-loop edge case."],
    [
      "duplicate edges",
      { n: 3, edges: [[0, 1], [0, 1], [1, 2]] },
      "depends-on-spec",
      "Tests dedupe and counting logic.",
    ],
    [
      "large sparse",
      { n: 1000, edges: Array.from({ length: 999 }, (_, i) => [i, i + 1]) },
      "depends-on-spec",
      "Stresses traversal efficiency.",
    ],
  ];
}

function casesByModel(model: InputModel, constraints: string[]) {
  if (model === "array") return generateArrayCases(constraints);
  if (model === "string") return generateStringCases();
  if (model === "matrix") return generateMatrixCases(constraints);
  if (model === "graph") return generateGraphCases();
  return generateNumberCases(constraints);
}

function expandToCount({
  curatedCases,
  fuzzCases,
  requiredCount,
}: {
  curatedCases: any[];
  fuzzCases: any[];
  requiredCount: number;
}) {
  const output: Array<{ category: string; input: unknown; expected: unknown; rationale: string }> = [];
  const seen = new Set<string>();

  const pushTuple = (tuple: any[], prefix: string | null) => {
    const [category, input, expected, rationale] = tuple;
    const key = stableKey(input);
    if (seen.has(key)) return;
    seen.add(key);
    output.push({ category: prefix ? `${prefix}: ${category}` : category, input, expected, rationale });
  };

  curatedCases.forEach((tuple) => pushTuple(tuple, null));
  fuzzCases.forEach((tuple) => pushTuple(tuple, "fuzz"));

  return output.slice(0, requiredCount);
}

function tupleToPlannedCase(tuple: [string, unknown, unknown, string]) {
  const [category, input, expected, rationale] = tuple;
  return { category, input, expected, rationale };
}

function buildFallbackPlannedCase({
  model,
  exampleInput,
  index,
}: {
  model: InputModel;
  exampleInput: unknown;
  index: number;
}) {
  if (exampleInput && typeof exampleInput === "object" && !Array.isArray(exampleInput)) {
    const baseInput = exampleInput as Record<string, unknown>;
    const nextInput: Record<string, unknown> = { ...baseInput };
    const keys = Object.keys(baseInput);
    const targetKey = keys[0] ?? "value";
    const currentValue = baseInput[targetKey];

    if (Array.isArray(currentValue)) {
      nextInput[targetKey] = [index, index + 1, index + 2];
    } else if (typeof currentValue === "number") {
      nextInput[targetKey] = index;
    } else if (typeof currentValue === "string") {
      nextInput[targetKey] = `fallback_${index}`;
    } else if (currentValue && typeof currentValue === "object" && Array.isArray((currentValue as any).matrix)) {
      nextInput[targetKey] = {
        ...(currentValue as any),
        matrix: [[index]],
      };
    } else if (currentValue && typeof currentValue === "object" && typeof (currentValue as any).n === "number" && Array.isArray((currentValue as any).edges)) {
      nextInput[targetKey] = {
        ...(currentValue as any),
        n: Math.max(1, index + 1),
        edges: index === 0 ? [] : [[0, 1]],
      };
    } else {
      nextInput[targetKey] = index;
    }

    return {
      category: `fallback ${targetKey}`,
      input: nextInput,
      rationale: "Last-resort unique filler to keep the generated case count exact.",
    };
  }

  if (model === "array") {
    return {
      category: "fallback array",
      input: { arr: [index, index + 1, index + 2] },
      rationale: "Last-resort unique filler to keep the generated case count exact.",
    };
  }

  if (model === "string") {
    return {
      category: "fallback string",
      input: { s: `fallback_${index}` },
      rationale: "Last-resort unique filler to keep the generated case count exact.",
    };
  }

  if (model === "matrix") {
    return {
      category: "fallback matrix",
      input: { matrix: [[index]] },
      rationale: "Last-resort unique filler to keep the generated case count exact.",
    };
  }

  if (model === "graph") {
    return {
      category: "fallback graph",
      input: { n: Math.max(1, index + 2), edges: index % 2 === 0 ? [] : [[0, 1]] },
      rationale: "Last-resort unique filler to keep the generated case count exact.",
    };
  }

  return {
    category: "fallback number",
    input: { n: index },
    rationale: "Last-resort unique filler to keep the generated case count exact.",
  };
}

function buildFuzzTuplesForModel({
  model,
  constraints,
  rng,
  targetCount,
}: {
  model: InputModel;
  constraints: string[];
  rng: () => number;
  targetCount: number;
}) {
  const tuples: any[] = [];
  const seen = new Set<string>();

  const push = (category: string, input: unknown, rationale: string) => {
    const key = stableKey(input);
    if (seen.has(key)) return;
    seen.add(key);
    tuples.push([category, input, "depends-on-spec", rationale]);
  };

  if (model === "array") {
    const arrays = generateArrayVariants(constraints, rng);
    arrays.forEach((arr) =>
      push(
        `array len=${arr.length}`,
        { arr },
        "Random/structured array variant to probe boundary and distribution behavior."
      )
    );
  } else if (model === "string") {
    const strings = generateStringVariants(rng);
    strings.forEach((s) =>
      push(`string len=${s.length}`, { s }, "Random/structured string variant to probe parsing and edge behavior.")
    );
  } else if (model === "matrix") {
    const matrices = generateMatrixVariants(constraints, rng);
    matrices.forEach((matrix) =>
      push(
        `matrix ${matrix.length}x${(matrix[0] ? matrix[0].length : 0) as number}`,
        { matrix },
        "Random/structured matrix variant to probe 2D boundary and performance behavior."
      )
    );
  } else if (model === "graph") {
    const graphs = generateGraphVariants(constraints, rng);
    graphs.forEach((g) =>
      push(
        `graph n=${g.n} m=${g.edges.length}`,
        { n: g.n, edges: g.edges },
        "Random/structured graph variant to probe traversal/cycle/connectivity behavior."
      )
    );
  } else {
    const nums = generateNumberVariants(constraints, rng);
    nums.forEach((n) =>
      push(`number n=${n}`, { n }, "Random/structured number variant to probe boundary arithmetic and validation behavior.")
    );
  }

  return tuples.slice(0, targetCount);
}

export function generateTestCases(payload: {
  challengeTitle: string;
  language: string;
  directions: string;
  referenceCode: string;
  requiredCount: number;
  exampleInput?: unknown;
}): GeneratedSuite {
  const { challengeTitle, language, directions, referenceCode, requiredCount, exampleInput } = payload;

  const constraintHints = extractConstraintHints(directions);
  const seed = fnv1a32(`${challengeTitle}::${directions}`);
  const rng = mulberry32(seed);

  const inferredFromExample = exampleInput ? inferModelFromExample(exampleInput) : null;
  const model = inferredFromExample || inferInputModel(directions, referenceCode);

  let plannedCases: Array<{ category: string; input: unknown; expected?: unknown; rationale: string }> = [];

  if (exampleInput && typeof exampleInput === "object" && !Array.isArray(exampleInput)) {
    plannedCases = buildMutatedObjectCases({
      baseInput: exampleInput as Record<string, unknown>,
      constraints: constraintHints,
      requiredCount,
      rng,
    });
  } else {
    const curatedCases = casesByModel(model, constraintHints);
    const fuzzCases = buildFuzzTuplesForModel({
      model,
      constraints: constraintHints,
      rng,
      targetCount: Math.max(0, requiredCount * 4),
    });

    plannedCases = expandToCount({
      curatedCases,
      fuzzCases,
      requiredCount,
    });
  }

  if (plannedCases.length < requiredCount) {
    const seenInputs = new Set(plannedCases.map((entry) => stableKey(entry.input)));

    // If the first pass dedupes too aggressively, keep generating until we hit the exact target.
    for (let attempt = 0; attempt < 4 && plannedCases.length < requiredCount; attempt += 1) {
      if (exampleInput && typeof exampleInput === "object" && !Array.isArray(exampleInput)) {
        const supplementalCases = buildMutatedObjectCases({
          baseInput: exampleInput as Record<string, unknown>,
          constraints: constraintHints,
          requiredCount: Math.max(requiredCount * 2, requiredCount + 32),
          rng,
        });

        for (const entry of supplementalCases) {
          if (plannedCases.length >= requiredCount) break;
          const key = stableKey(entry.input);
          if (seenInputs.has(key)) continue;
          seenInputs.add(key);
          plannedCases.push(entry);
        }
      } else {
        const supplementalTuples = buildFuzzTuplesForModel({
          model,
          constraints: constraintHints,
          rng,
          targetCount: Math.max(requiredCount * 4, requiredCount + 64),
        });

        for (const tuple of supplementalTuples) {
          if (plannedCases.length >= requiredCount) break;
          const entry = tupleToPlannedCase(tuple);
          const key = stableKey(entry.input);
          if (seenInputs.has(key)) continue;
          seenInputs.add(key);
          plannedCases.push(entry);
        }
      }
    }

    let fallbackIndex = plannedCases.length;
    while (plannedCases.length < requiredCount) {
      const fallbackCase = buildFallbackPlannedCase({
        model,
        exampleInput,
        index: fallbackIndex,
      });
      fallbackIndex += 1;

      const key = stableKey(fallbackCase.input);
      if (seenInputs.has(key)) continue;
      seenInputs.add(key);
      plannedCases.push(fallbackCase);
    }
  }

  plannedCases = plannedCases.slice(0, requiredCount);

  const testCases = plannedCases.map((entry, idx) =>
    buildCase(
      `TC-${String(idx + 1).padStart(4, "0")}`,
      entry.category,
      entry.input,
      entry.expected ?? "depends-on-spec",
      entry.rationale
    )
  );

  return {
    metadata: {
      challengeTitle,
      language,
      inferredInputModel: model,
      requiredCount,
      generatedCount: testCases.length,
      constraintHints,
      seed,
      generatedAt: new Date().toISOString(),
      note:
        "Expected outputs are placeholders unless you enable reference execution. Always validate final answers with a trusted solution before grading.",
    },
    testCases,
  };
}
